# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02cf2292ea95f5e2cf019764e120f8d2819efbf76b6a836902e1a70c1894a58a168a081872a361b6a83e5dc5e3c1578718bc40ac10aef3055c8675eadeb51d3a

test:
  secret_key_base: 54248248d401fa30dd865f5949e718354f60c75d5aeb525140d6fbde089b95fb1c97f78506b80894beef994f6b9689d605617fb56fabc084bcf48ff0306d3965

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
